name: Deploy to GitHub Pages

# Run workflow on every push to the master branch
on:
  push:
    branches: [ main ]

jobs:
  deploy-to-github-pages:
    # use ubuntu-latest image to run steps on
    runs-on: ubuntu-latest
    steps:
    # uses GitHub's checkout action to checkout code form the master branch
    - uses: actions/checkout@v2.3.4

    # sets up .NET Core SDK 3.1
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 5.0.100

    # changes the base-tag in index.html from '/' to 'BlazorAnalyticsTest' to match GitHub Pages repository subdirectory
    - name: Change base-tag in index.html from / to BlazorAnalyticsTest
      run: sed -i 's/<base href="\/" \/>/<base href="\/BlazorAnalyticsTest\/" \/>/g' wwwroot/index.html

    # publishes Blazor project to the release-folder
    - name: Publish .NET Core Project
      run: dotnet publish BlazorAnalyticsTest.csproj -c Release -o release -p:BlazorEnableCompression=false --nologo

    - name: Commit wwwroot to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: release/wwwroot
